version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app_v1
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root:root_password@db:3306/RESTfulAPISymfony
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: RESTfulAPISymfony
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: RESTfulAPISymfony
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  db_data:

  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
